sudo: false
language: objective-c
osx_image: xcode8
script:
- xcodebuild clean build test -workspace LDSContent.xcworkspace -scheme LDSContent -sdk iphonesimulator -destination "OS=10.0,name=iPhone 5,platform=iOS Simulator"
- pod lib lint --verbose
